"""add_role_to_user_model

Revision ID: 5e9c062c3940
Revises: f2b823dbb5ba
Create Date: 2025-06-18 15:07:16.437561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e9c062c3940"
down_revision: Union[str, None] = "f2b823dbb5ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum("ADMIN", "USER", name="role")
    role_enum.create(op.get_bind(), checkfirst=False)

    op.add_column(
        "users", sa.Column("role", role_enum, nullable=False, server_default="USER")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    role_enum = sa.Enum("ADMIN", "USER", name="role")
    role_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
