"""add created_at and updated_at

Revision ID: a4d43badfc33
Revises: 40c83d640fb3
Create Date: 2025-06-05 22:25:23.875105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d43badfc33'
down_revision: Union[str, None] = '40c83d640fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
